/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/deer.gltf');
  const { actions } = useAnimations(animations, group);

  console.log(animations);
  useEffect(() => {
    actions.Idle.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 2.84, -0.65]}>
        <primitive object={nodes.Main} />
        <skinnedMesh
          geometry={nodes.Body.geometry}
          material={materials.body}
          skeleton={nodes.Body.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Eyes.geometry}
          material={materials.Eye}
          skeleton={nodes.Eyes.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Head_1.geometry}
          material={materials.head}
          skeleton={nodes.Head_1.skeleton}
        />
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        scale={8.78}
      />
    </group>
  );
}

useGLTF.preload('/deer.gltf');
